//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ActorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Actor), typeof(System.Object));
		L.RegFunction("Init", Init);
		L.RegFunction("DropBind", DropBind);
		L.RegFunction("DropWeapon", DropWeapon);
		L.RegFunction("UpdateBind", UpdateBind);
		L.RegFunction("UpdateWeapon", UpdateWeapon);
		L.RegFunction("New", _CreateActor);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateActor(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
				Actor obj = new Actor(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Actor.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Actor obj = (Actor)ToLua.CheckObject<Actor>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DropBind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Actor obj = (Actor)ToLua.CheckObject<Actor>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.DropBind(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DropWeapon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Actor obj = (Actor)ToLua.CheckObject<Actor>(L, 1);
			obj.DropWeapon();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateBind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Actor obj = (Actor)ToLua.CheckObject<Actor>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateBind(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateWeapon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Actor obj = (Actor)ToLua.CheckObject<Actor>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateWeapon(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

