//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class C2S_BuyItemWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(C2S_BuyItem), typeof(System.Object));
		L.RegFunction("New", _CreateC2S_BuyItem);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("itemId", get_itemId, set_itemId);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateC2S_BuyItem(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				C2S_BuyItem obj = new C2S_BuyItem(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: C2S_BuyItem.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_itemId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			C2S_BuyItem obj = (C2S_BuyItem)o;
			int ret = obj.itemId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_itemId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			C2S_BuyItem obj = (C2S_BuyItem)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.itemId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemId on a nil value");
		}
	}
}

