//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class C2S_CheckRankWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(C2S_CheckRank), typeof(System.Object));
		L.RegFunction("New", _CreateC2S_CheckRank);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("rankType", get_rankType, set_rankType);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateC2S_CheckRank(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				C2S_CheckRank obj = new C2S_CheckRank(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: C2S_CheckRank.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_rankType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			C2S_CheckRank obj = (C2S_CheckRank)o;
			int ret = obj.rankType;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rankType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_rankType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			C2S_CheckRank obj = (C2S_CheckRank)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.rankType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rankType on a nil value");
		}
	}
}

