//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Net_Share_RpcWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Net.Share.Rpc), typeof(Net.Share.RPCFun));
		L.RegFunction("New", _CreateNet_Share_Rpc);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNet_Share_Rpc(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Net.Share.Rpc obj = new Net.Share.Rpc();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				byte arg0 = (byte)LuaDLL.luaL_checknumber(L, 1);
				Net.Share.Rpc obj = new Net.Share.Rpc(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Net.Share.Rpc.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

