//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_InitBattlersWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_InitBattlers), typeof(System.Object));
		L.RegFunction("New", _CreateS2C_InitBattlers);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("rolesDic", get_rolesDic, set_rolesDic);
		L.RegVar("battlersInfo", get_battlersInfo, set_battlersInfo);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_InitBattlers(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				S2C_InitBattlers obj = new S2C_InitBattlers();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_InitBattlers.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_rolesDic(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_InitBattlers obj = (S2C_InitBattlers)o;
			System.Collections.Generic.Dictionary<string,byte> ret = obj.rolesDic;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rolesDic on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_battlersInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_InitBattlers obj = (S2C_InitBattlers)o;
			System.Collections.Generic.List<S2C_BattlerInfo> ret = obj.battlersInfo;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index battlersInfo on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_rolesDic(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_InitBattlers obj = (S2C_InitBattlers)o;
			System.Collections.Generic.Dictionary<string,byte> arg0 = (System.Collections.Generic.Dictionary<string,byte>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,byte>));
			obj.rolesDic = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rolesDic on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_battlersInfo(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_InitBattlers obj = (S2C_InitBattlers)o;
			System.Collections.Generic.List<S2C_BattlerInfo> arg0 = (System.Collections.Generic.List<S2C_BattlerInfo>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<S2C_BattlerInfo>));
			obj.battlersInfo = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index battlersInfo on a nil value");
		}
	}
}

