//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_UpdateBattlesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_UpdateBattles), typeof(System.Object));
		L.RegFunction("New", _CreateS2C_UpdateBattles);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("updateBattles", get_updateBattles, set_updateBattles);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_UpdateBattles(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				System.Collections.Generic.List<S2C_UpdateBattle> arg0 = (System.Collections.Generic.List<S2C_UpdateBattle>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<S2C_UpdateBattle>));
				S2C_UpdateBattles obj = new S2C_UpdateBattles(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_UpdateBattles.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_updateBattles(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_UpdateBattles obj = (S2C_UpdateBattles)o;
			System.Collections.Generic.List<S2C_UpdateBattle> ret = obj.updateBattles;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index updateBattles on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_updateBattles(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_UpdateBattles obj = (S2C_UpdateBattles)o;
			System.Collections.Generic.List<S2C_UpdateBattle> arg0 = (System.Collections.Generic.List<S2C_UpdateBattle>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<S2C_UpdateBattle>));
			obj.updateBattles = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index updateBattles on a nil value");
		}
	}
}

