//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_LoginOrRegisterCallbackWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_LoginOrRegisterCallback), typeof(System.Object));
		L.RegFunction("New", _CreateS2C_LoginOrRegisterCallback);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("result", get_result, set_result);
		L.RegVar("message", get_message, set_message);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_LoginOrRegisterCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
				string arg1 = ToLua.CheckString(L, 2);
				S2C_LoginOrRegisterCallback obj = new S2C_LoginOrRegisterCallback(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_LoginOrRegisterCallback.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_result(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_LoginOrRegisterCallback obj = (S2C_LoginOrRegisterCallback)o;
			bool ret = obj.result;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index result on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_message(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_LoginOrRegisterCallback obj = (S2C_LoginOrRegisterCallback)o;
			string ret = obj.message;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index message on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_result(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_LoginOrRegisterCallback obj = (S2C_LoginOrRegisterCallback)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.result = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index result on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_message(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_LoginOrRegisterCallback obj = (S2C_LoginOrRegisterCallback)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.message = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index message on a nil value");
		}
	}
}

