//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_RoundWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_Round), typeof(System.Object));
		L.RegFunction("New", _CreateS2C_Round);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("round", get_round, set_round);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_Round(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				byte arg0 = (byte)LuaDLL.luaL_checknumber(L, 1);
				S2C_Round obj = new S2C_Round(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_Round.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_round(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_Round obj = (S2C_Round)o;
			byte ret = obj.round;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index round on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_round(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_Round obj = (S2C_Round)o;
			byte arg0 = (byte)LuaDLL.luaL_checknumber(L, 2);
			obj.round = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index round on a nil value");
		}
	}
}

