//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_MainRoleInfoWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_MainRoleInfo), typeof(S2C_OtherRoleInfo));
		L.RegFunction("New", _CreateS2C_MainRoleInfo);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("hp", get_hp, set_hp);
		L.RegVar("maxHp", get_maxHp, set_maxHp);
		L.RegVar("mp", get_mp, set_mp);
		L.RegVar("maxMp", get_maxMp, set_maxMp);
		L.RegVar("physicalAttack", get_physicalAttack, set_physicalAttack);
		L.RegVar("physicalDefense", get_physicalDefense, set_physicalDefense);
		L.RegVar("magicAttack", get_magicAttack, set_magicAttack);
		L.RegVar("magicDefense", get_magicDefense, set_magicDefense);
		L.RegVar("speed", get_speed, set_speed);
		L.RegVar("experience", get_experience, set_experience);
		L.RegVar("silver", get_silver, set_silver);
		L.RegVar("gold", get_gold, set_gold);
		L.RegVar("yuanBao", get_yuanBao, set_yuanBao);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_MainRoleInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 25)
			{
				string arg0 = ToLua.CheckString(L, 1);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg3 = (int)LuaDLL.luaL_checknumber(L, 4);
				string arg4 = ToLua.CheckString(L, 5);
				bool arg5 = LuaDLL.luaL_checkboolean(L, 6);
				bool arg6 = LuaDLL.luaL_checkboolean(L, 7);
				int arg7 = (int)LuaDLL.luaL_checknumber(L, 8);
				int arg8 = (int)LuaDLL.luaL_checknumber(L, 9);
				int arg9 = (int)LuaDLL.luaL_checknumber(L, 10);
				int arg10 = (int)LuaDLL.luaL_checknumber(L, 11);
				UnityEngine.Vector3 arg11 = ToLua.ToVector3(L, 12);
				int arg12 = (int)LuaDLL.luaL_checknumber(L, 13);
				int arg13 = (int)LuaDLL.luaL_checknumber(L, 14);
				int arg14 = (int)LuaDLL.luaL_checknumber(L, 15);
				int arg15 = (int)LuaDLL.luaL_checknumber(L, 16);
				int arg16 = (int)LuaDLL.luaL_checknumber(L, 17);
				int arg17 = (int)LuaDLL.luaL_checknumber(L, 18);
				int arg18 = (int)LuaDLL.luaL_checknumber(L, 19);
				int arg19 = (int)LuaDLL.luaL_checknumber(L, 20);
				int arg20 = (int)LuaDLL.luaL_checknumber(L, 21);
				int arg21 = (int)LuaDLL.luaL_checknumber(L, 22);
				int arg22 = (int)LuaDLL.luaL_checknumber(L, 23);
				int arg23 = (int)LuaDLL.luaL_checknumber(L, 24);
				int arg24 = (int)LuaDLL.luaL_checknumber(L, 25);
				S2C_MainRoleInfo obj = new S2C_MainRoleInfo(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_MainRoleInfo.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.hp;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_maxHp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.maxHp;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index maxHp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.mp;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_maxMp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.maxMp;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index maxMp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_physicalAttack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.physicalAttack;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index physicalAttack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_physicalDefense(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.physicalDefense;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index physicalDefense on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_magicAttack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.magicAttack;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index magicAttack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_magicDefense(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.magicDefense;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index magicDefense on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_speed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.speed;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index speed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_experience(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.experience;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index experience on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_silver(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.silver;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index silver on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_gold(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.gold;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index gold on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_yuanBao(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int ret = obj.yuanBao;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yuanBao on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.hp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_maxHp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.maxHp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index maxHp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.mp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_maxMp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.maxMp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index maxMp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_physicalAttack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.physicalAttack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index physicalAttack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_physicalDefense(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.physicalDefense = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index physicalDefense on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_magicAttack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.magicAttack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index magicAttack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_magicDefense(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.magicDefense = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index magicDefense on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_speed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.speed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index speed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_experience(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.experience = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index experience on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_silver(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.silver = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index silver on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_gold(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.gold = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index gold on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_yuanBao(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_MainRoleInfo obj = (S2C_MainRoleInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.yuanBao = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yuanBao on a nil value");
		}
	}
}

