//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_AddSkillsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_AddSkills), typeof(System.Object));
		L.RegFunction("New", _CreateS2C_AddSkills);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("skills", get_skills, set_skills);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_AddSkills(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				System.Collections.Generic.List<S2C_AddSkill> arg0 = (System.Collections.Generic.List<S2C_AddSkill>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<S2C_AddSkill>));
				S2C_AddSkills obj = new S2C_AddSkills(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_AddSkills.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_skills(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_AddSkills obj = (S2C_AddSkills)o;
			System.Collections.Generic.List<S2C_AddSkill> ret = obj.skills;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index skills on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_skills(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_AddSkills obj = (S2C_AddSkills)o;
			System.Collections.Generic.List<S2C_AddSkill> arg0 = (System.Collections.Generic.List<S2C_AddSkill>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<S2C_AddSkill>));
			obj.skills = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index skills on a nil value");
		}
	}
}

