//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class S2C_RemoveItemsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(S2C_RemoveItems), typeof(System.Object));
		L.RegFunction("New", _CreateS2C_RemoveItems);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Guids", get_Guids, set_Guids);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateS2C_RemoveItems(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				System.Collections.Generic.List<S2C_RemoveItemInfo> arg0 = (System.Collections.Generic.List<S2C_RemoveItemInfo>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<S2C_RemoveItemInfo>));
				S2C_RemoveItems obj = new S2C_RemoveItems(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: S2C_RemoveItems.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Guids(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_RemoveItems obj = (S2C_RemoveItems)o;
			System.Collections.Generic.List<S2C_RemoveItemInfo> ret = obj.Guids;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Guids on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Guids(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			S2C_RemoveItems obj = (S2C_RemoveItems)o;
			System.Collections.Generic.List<S2C_RemoveItemInfo> arg0 = (System.Collections.Generic.List<S2C_RemoveItemInfo>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<S2C_RemoveItemInfo>));
			obj.Guids = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Guids on a nil value");
		}
	}
}

